name: OpenWrt Builder

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: openwrt-24.10
  CONFIG_FILE: .config
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: 释放磁盘空间
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        swap-storage: true

    - name: 初始化编译环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh)'
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: 获取源码
      working-directory: /workdir
      run: |
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: 更新软件源
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: 添加模组插件
      run: |
        cd openwrt
        echo 'src-git modem https://github.com/FUjr/modem_feeds.git;main' >> feeds.conf.default
        ./scripts/feeds update modem
        ./scripts/feeds install -a -p modem

    - name: 加载模组驱动
      run: |
        cd openwrt
        echo 'src-git lede https://github.com/coolsnowwolf/lede;master' >> feeds.conf.default
        ./scripts/feeds update lede
        ./scripts/feeds install quectel_MHI

    - name: 导入配置文件
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config

    - name: 下载依赖
      run: |
        cd openwrt
        make oldconfig
        make download -j8
        find dl -size -1024c -exec rm -f {} \;

    - name: 编译固件
      run: |
        cd openwrt
        make -j$(($(nproc) + 1)) || make -j1 V=s
        echo "FIRMWARE_PATH=openwrt/bin/targets/*/*" >> $GITHUB_ENV

    - name: 发布固件
      uses: softprops/action-gh-release@v1
      with:
        tag_name: nightly-${{ github.run_id }}
        files: ${{ env.FIRMWARE_PATH }}/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


